using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PB
{
    // Total PB Values
    public const float EXPECTED_TOTAL_PB_FROM_ITEMS_AT_LEVEL_50 = 21 * MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER5_PB; //525
    public const float EXPECTED_TOTAL_PB_FROM_SKILL_TREE_AT_LEVEL_50 = 22 * ENERGY_LEVEL_3_MULTIPLIER * SPECIALITY_SKILL_TREE_PB + 22 * ENERGY_LEVEL_2_MULTIPLIER * SPECIALITY_SKILL_TREE_PB + 5 * ENERGY_LEVEL_1_MULTIPLIER * SPECIALITY_SKILL_TREE_PB + ENERGY_LEVEL_3_MULTIPLIER * ROW12_HEAL_POWER_UP_PB; // 574 + 40 = 614
    public const float EXPECTED_TOTAL_PB_FROM_STANCE_AT_LEVEL_50 = 200; // 70 base + 40 upg1 + 40 upg2 + 70 upg3
    public const float EXPECTED_TOTAL_PB_FROM_PERMANENT_POWER_UPS_AT_LEVEL_50 = 3 * 5 * MISSION_POWER_UPS_PB_BUDGET; //225
    //1564 Total at lvl 50

    public const float EXPECTED_PERCENTAGE_OF_DAMAGE_DEALT_COMING_FROM_BASIC_ATTACKS = 20;
    public const float EXPECTED_PERCENTAGE_OF_DAMAGE_DEALT_COMING_FROM_TECHNIQUES = 40;
    public const float EXPECTED_PERCENTAGE_OF_DAMAGE_DEALT_COMING_FROM_RIPOSTES = 10;
    public const float EXPECTED_PERCENTAGE_OF_DAMAGE_DEALT_COMING_FROM_COUNTERS = 10;
    public const float EXPECTED_PERCENTAGE_OF_DAMAGE_DEALT_COMING_FROM_TOOLS = 10;
    public const float EXPECTED_PERCENTAGE_OF_DAMAGE_DEALT_COMING_FROM_SPECIAL_EFFECTS = 10;

    // Skill Tree Node PB Values
    public const float NON_SPECIALITY_SKILL_TREE_PB = 5; // Final Intended is 5
    public const float SPECIALITY_SKILL_TREE_PB = 7; // Final Intended is 7
    public const float ROW12_HEAL_POWER_UP_PB = 15;
    public const float ENERGY_LEVEL_1_MULTIPLIER = 1.2f;
    public const float ENERGY_LEVEL_2_MULTIPLIER = 1.5f;
    public const float ENERGY_LEVEL_3_MULTIPLIER = 2.0f;
    public const float MISSION_POWER_UPS_PB_BUDGET = 15;
    public const float STANCE_DEFAULT_PB = 70;
    public const float STANCE_UPGRADE_1_DEFAULT_PB = 40;
    public const float STANCE_UPGRADE_2_DEFAULT_PB = 40;
    public const float STANCE_UPGRADE_3_DEFAULT_PB = 70;


    // Item PB Values
    public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER1_PB = 40;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER1_PB = 0;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER1_PB = 20;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER1_PB = 0;
    public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER2_PB = 50;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER2_PB = 0;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER2_PB = 25;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER2_PB = 0;
    public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER3_PB = 60;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER3_PB = 30;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER3_PB = 30;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER3_PB = 15;
    public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER4_PB = 80;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER4_PB = 40;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER4_PB = 40;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER4_PB = 20f;
    public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER5_PB = 100;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER5_PB = 50;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER5_PB = 50;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER5_PB = 25;

    /*public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER1_PB = 20;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER1_PB = 0;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER1_PB = 10;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER1_PB = 0;
    public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER2_PB = 40;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER2_PB = 0;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER2_PB = 20;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER2_PB = 0;
    public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER3_PB = 50;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER3_PB = 20;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER3_PB = 25;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER3_PB = 10;
    public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER4_PB = 70;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER4_PB = 35;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER4_PB = 35;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER4_PB = 17.5f;
    public const float MAJOR_ITEM_FIRST_EFFECT_LINEAR_TIER5_PB = 100;
    public const float MAJOR_ITEM_SECOND_EFFECT_LINEAR_TIER5_PB = 50;
    public const float MINOR_ITEM_FIRST_EFFECT_LINEAR_TIER5_PB = 50;
    public const float MINOR_ITEM_SECOND_EFFECT_LINEAR_TIER5_PB = 25;*/

    //Multipliers for requiring certain event to happen to activate
    public const float HAPPENS_UPON__DODGING = 1.75f;
    public const float HAPPENS_UPON__BLOCKING = 1.5f;
    public const float HAPPENS_UPON__RIPOSTING = 2.5f;
    public const float HAPPENS_UPON__COUNTERING = 5f;
    public const float HAPPENS_UPON__RIPOSTING_OR_COUNTERING = 2.4f;
    public const float HAPPENS_UPON__DODGING_RIPOSTING_OR_COUNTERING = 1.5f;
    public const float HAPPENS_UPON__DEALING_MAGIC_DAMAGE = 2f;
    public const float HAPPENS_UPON__DEALING_ANY_WEAPON_DAMAGE = 1.5f;
    public const float HAPPENS_UPON__DEALING_SPECIFIC_WEAPON_DAMAGE = 2f;
    public const float HAPPENS_UPON__USING_TECHNIQUE = 1.8f;
    public const float HAPPENS_UPON__USING_WEAPON_TECHNIQUE = 2.2f;
    public const float HAPPENS_UPON__USING_MAGIC_TECHNIQUE = 2.2f;
    public const float HAPPENS_UPON__GAINING_ENEGY = 1.4f;
    public const float HAPPENS_UPON__USING_TOOL = 4.5f;
    public const float HAPPENS_UPON__BASIC_ATTACKING = 1.5f;
    public const float HAPPENS_UPON__BASIC_ATTACKING_OR_DODGING = 1.35f;
    public const float HAPPENS_UPON__STRONG_BASIC_ATTACKING = 3.5f;
    public const float HAPPENS_UPON__BACKSTABING = 3.5f;
    public const float HAPPENS_UPON__STAGGERING_AN_ENEMY = 3.5f;
    public const float HAPPENS_UPON__FREEZING_AN_ENEMY = 4f;
    public const float HAPPENS_UPON__ENEMY_EXITING_STAGGERED = 4f;
    public const float HAPPENS_UPON__TAKEDOWN = 5f;
    public const float HAPPENS_UPON__DEALING_DAMAGE = 1.75f;
    public const float HAPPENS_UPON__DEALING_OR_TAKING_DAMAGE = 1.5f;
    public const float HAPPENS_UPON__BEING_DEBUFFED = 3.5f;
    public const float HAPPENS_UPON__GETTING_DAMAGED = 2.0f;
    public const float HAPPENS_UPON__GETTING_DAMAGED_FROM_BEHIND = 3.5f;
    public const float HAPPENS_UPON__PLAYER_SUFFERING_A_FATAL_BLOW = 2.25f;
    public const float HAPPENS_UPON__PLAYER_FALLING_BELOW_25P_HEALTH = 3f;
    public const float HAPPENS_UPON__PLAYER_FALLING_BELOW_50P_HEALTH = 2f;
    public const float HAPPENS_UPON__SWITCHING_OUT_OF_THE_STANCE = 2.5f;

    //Multipliers for only affecting specified situations
    public const float AFFECTS_ONLY__ONCE = 2.5f;
    public const float AFFECTS_ONLY__5_SECONDS_AFTER_RIPOSTE_OR_10_SECONDS_AFTER_COUNTER = 2.5f;
    public const float AFFECTS_ONLY__PLAYER_CROWD_CONTROLLED = 4f;
    public const float AFFECTS_ONLY__WORKS_10_SECONDS_NON_STACKABLE = 3f;
    public const float AFFECTS_ONLY__WORKS_30_SECONDS_NON_STACKABLE = 1.7f;
    public const float AFFECTS_ONLY__ENEMY_EMPTY_STAGGER_BAR = 6.5f;
    public const float AFFECTS_ONLY__ENEMY_NO_STACKING_EFFECT_APPLIED = 5f;
    public const float AFFECTS_ONLY__STUN_CANNOT_EXCEED_DOUBLE_ITS_ORIGINAL_LENGTH = 2.0f;
    public const float AFFECTS_ONLY__ENEMY_BELOW_25P_HEALTH = 6f;
    public const float AFFECTS_ONLY__ENEMIES_WITHIN_3M_RANGE = 0.5f;
    public const float AFFECTS_ONLY__ENEMIES_WITH_ENOUGH_BLEED_TO_FINISH_THEM_OFF_OVER_ITS_DURATION = 6f;
    public const float AFFECTS_ONLY__ENEMIES_WITHOUT_ARMOR = 1.75f;
    public const float AFFECTS_ONLY__ENEMY_ABOVE_50P_STAGGER_BAR = 2.5f;
    public const float AFFECTS_ONLY__PLAYER_BELOW_25P_HEALTH = 3.5f;
    public const float AFFECTS_ONLY__PLAYER_ABOVE_50P_HEALTH = 1.3f;
    public const float AFFECTS_ONLY__PLAYER_BELOW_50P_HEALTH = 1.8f;
    public const float AFFECTS_ONLY__EFFECT_TRIPLED_WHILE_BELOW_50P_HEALTH = 0.55f;
    public const float AFFECTS_ONLY__PLAYER_ABOVE_50P_STAGGER_BAR = 3.5f;
    public const float AFFECTS_ONLY__ENEMY_WHO_LANDED_FATAL_BLOW = 1.75f;
    public const float AFFECTS_ONLY__RIPOSTES_AND_COUNTERS = 3f;
    public const float AFFECTS_ONLY__RIPOSTES = 5f;
    public const float AFFECTS_ONLY__COUNTERS = 5f;
    public const float AFFECTS_ONLY__WEAPON_DAMAGE = 1.2f;
    public const float AFFECTS_ONLY__MAGIC_DAMAGE = 1.2f;
    public const float AFFECTS_ONLY__EVERYTHING_EXCEPT_TECHNIQUES = 1.2f;
    public const float AFFECTS_ONLY__TECHNIQUES = 1.55f;
    public const float AFFECTS_ONLY__SPECIFIED_WEAPON_TECHNIQUES = 2f;
    public const float AFFECTS_ONLY__ULTIMATE_TECHNIQUES = 3.25f;
    public const float AFFECTS_ONLY__FAMILY_TECHNIQUES = 1.85f;
    public const float AFFECTS_ONLY__STOLEN_TECHNIQUES = 2.7f;
    public const float AFFECTS_ONLY__COOLDOWN_REDUCTION_FOR_TECHNIQUES = 1.5f;
    public const float AFFECTS_ONLY__COOLDOWNS_OF_TECHNIQUES_IN_OTHER_STANCES = 1.35f;
    public const float AFFECTS_ONLY__TOOL_DAMAGE = 4f;
    public const float AFFECTS_ONLY__COOLDOWN_REDUCTION_FOR_TOOLS = 2.1f;
    public const float AFFECTS_ONLY__COOLDOWN_REDUCTION_FOR_EFFECTS = 2.25f;
    public const float AFFECTS_ONLY__5TH_ATTACK = 3f;
    public const float AFFECTS_ONLY__STRONG_BASIC_ATTACKS = 3.5f;
    public const float AFFECTS_ONLY__BASIC_ATTACKS = 1.75f;
    public const float AFFECTS_ONLY__BASIC_ATTACKS_RIPOSTES_AND_COUNTERS = 1.4f;
    public const float AFFECTS_ONLY__BACKSTABS = 3f;
    public const float AFFECTS_ONLY__INJURY = 1.4f;
    public const float AFFECTS_ONLY__STAGGER = 1.4f;
    public const float AFFECTS_ONLY__WEAPON_TYPE = 1.4f;
    public const float AFFECTS_ONLY__COUNTERABLE = 3f;
    public const float AFFECTS_ONLY__UNSTOPPABLE = 3f;
    public const float AFFECTS_ONLY__STAGGERED = 2.5f;
    public const float AFFECTS_ONLY__SLEEPING = 7f;
    public const float AFFECTS_ONLY__STUNNED = 2.2f;
    public const float AFFECTS_ONLY__FROZEN = 3.25f;
    public const float AFFECTS_ONLY__CROWD_CONTROLLED = 2.5f;
    public const float AFFECTS_ONLY__NON_STAGGERED = 1.75f;
    public const float AFFECTS_ONLY__BOSSES = 2f;
    public const float AFFECTS_ONLY__NON_BOSSES = 2f;
    public const float AFFECTS_ONLY__PLAYER_STACKING_EFFECT_DAMAGE = 5f;
    public const float AFFECTS_ONLY__ONE_STANCE = 1.5f;
    public const float AFFECTS_ONLY__FINAL_AMMO = 5.5f;
    public const float AFFECTS_ONLY__ENERGY_GAIN_FROM_HEALTH_LOST = 3.5f;
    public const float AFFECTS_ONLY__ENERGY_GAIN_FROM_BLOCKING = 4f;
    public const float AFFECTS_ONLY__ENERGY_GAIN_FROM_BASIC_ATTACKS = 2.5f;
    public const float AFFECTS_ONLY__ENERGY_GAIN_FROM_DODGING = 6f;
    public const float AFFECTS_ONLY__ENERGY_GAIN_FROM_RIPOSTING = 10f;
    public const float AFFECTS_ONLY__ENERGY_GAIN_FROM_COUNTERING = 10f;
    public const float AFFECTS_ONLY__ENERGY_GAIN_FROM_STAGGERING = 8f;
    public const float AFFECTS_ONLY__SUPERCHARGE_DAMAGE = 5.0f;
    public const float AFFECTS_ONLY__BURN_DAMAGE = 4f;
    public const float AFFECTS_ONLY__BURN_EXPLOSION_DAMAGE = 8f;
    public const float AFFECTS_ONLY__ENEMY_STACKING_EFFECT_DAMAGE = 20f;
    public const float AFFECTS_ONLY__5_SECONDS = 2.0f;
    public const float AFFECTS_ONLY__10_SECONDS = 1.75f;
    public const float AFFECTS_ONLY__15_SECONDS = 1.5f;
    public const float AFFECTS_ONLY__20_SECONDS = 1.4f;
    public const float AFFECTS_ONLY__30_SECONDS = 1.25f;
    public const float AFFECTS_ONLY__PLAYER_BASIC_ATTACKING = 2.35f;
    public const float AFFECTS_ONLY__PLAYER_ATTACKING = 1.75f;
    public const float AFFECTS_ONLY__TECHNIQUE_FROM_RANDOMLY_SELECTED_FAMILY = 2.5f;


    //Multipliers for requiring special restrictions
    public const float REQUIRES__ASSASSINATION_PREPARED = 2.0f;
    public const float REQUIRES__USING_TECHNIQUES_FROM_7_RANDOMLY_SELECTED_FAMILIES = 7.0f;
    public const float REQUIRES__10_SECONDS_WITHOUT_ATTACKING_FOR_FULL_VALUE = 3.0f;
    public const float REQUIRES__60_SECONDS_IN_COMBAT_FOR_FULL_VALUE = 2.5f;
    public const float REQUIRES__ENEMY_USING_FAMILY_TECHNIQUE = 1.5f;
    public const float REQUIRES__BELOW_1_AMMO = 2.0f;
    private const float REQUIRES__SPECIFIC_EFFECT = 1.5f;
    public const float REQUIRES__SHARP = REQUIRES__SPECIFIC_EFFECT * 1.0f;
    public const float REQUIRES__BURN = REQUIRES__SPECIFIC_EFFECT * 1.15f;
    public const float REQUIRES__FREEZE = REQUIRES__SPECIFIC_EFFECT * 1.15f;
    public const float REQUIRES__BARRIER = REQUIRES__SPECIFIC_EFFECT * 1.25f;
    public const float REQUIRES__BLEED = REQUIRES__SPECIFIC_EFFECT * 1.1f;
    public const float REQUIRES__SUPERCHARGE = REQUIRES__SPECIFIC_EFFECT * 1.25f;
    public const float REQUIRES__ANALYSIS = REQUIRES__SPECIFIC_EFFECT * 1.0f;
    public const float REQUIRES__CHAINED = REQUIRES__SPECIFIC_EFFECT * 1.25f;
    public const float REQUIRES__STEALTH = REQUIRES__SPECIFIC_EFFECT * 3f;
    public const float REQUIRES__3_SECOND_COOLDOWN = 1.35f;
    public const float REQUIRES__5_SECOND_COOLDOWN = 1.5f;
    public const float REQUIRES__10_SECOND_COOLDOWN = 1.75f;
    public const float REQUIRES__15_SECOND_COOLDOWN = 2f;
    public const float REQUIRES__20_SECOND_COOLDOWN = 2.2f;
    public const float REQUIRES__30_SECOND_COOLDOWN = 2.5f;
    public const float REQUIRES__45_SECOND_COOLDOWN_UPON_BEING_CCED = 3.25f;
    public const float REQUIRES__45_SECOND_COOLDOWN = 2.75f;
    public const float REQUIRES__60_SECOND_COOLDOWN = 3f;
    public const float REQUIRES__90_SECOND_COOLDOWN = 3.25f;
    public const float REQUIRES__120_SECOND_COOLDOWN = 3.5f;
    public const float REQUIRES__300_SECOND_COOLDOWN = 4f;
    public const float REQUIRES__MAX_VALUE_WHEN_ENEMY_IS_15M_AWAY = 3f;
    public const float REQUIRES__LOSING_1P_CURRENT_HEALTH_EACH_SECOND = 5f;
    public const float REQUIRES__CONSUMING_1P_OF_STACKING_EFFECT = 1.5f;
    public const float REQUIRES__CONSUMING_ALL_SCALING_STACKING_EFFECT_WHEN_USED = 2.5f;
    public const float REQUIRES__PLAYER_DEBUFFED = 2f;
    public const float REQUIRES__PLAYER_STAGGERED = 3f;
    public const float REQUIRES__ANY_ENEMY_IS_IN_5M_RANGE = 1.75f;
    public const float REQUIRES__GIVEN_ENEMY_IS_IN_5M_RANGE = 2f;
    public const float REQUIRES__GIVEN_ENEMY_IS_AT_LEAST_5M_AWAY = 2f;
    public const float REQUIRES__PLAYER_WAS_DAMAGED_IN_LAST_10_SECONDS = 2.5f;
    public const float REQUIRES__PLAYER_FULL_HEALTH = 2.6f;
    public const float REQUIRES__PLAYER_BELOW_HALF_HEALTH = 1.8f;
    public const float REQUIRES__PLAYER_BELOW_33P_HEALTH = 2.4f;
    public const float REQUIRES__PLAYER_ABOVE_HALF_STAGGER_BAR = 1.8f;
    public const float REQUIRES__PLAYER_ABOVE_66P_STAGGER_BAR = 2.4f;
    public const float REQUIRES__SPECIFIC_ITEM_EQUIPPED = 3.0f;
    public const float REQUIRES__HITTING_SPAWNED_MARK = 4.0f;
    public const float REQUIRES__REMAINING_IN_THE_STANCE = 2f;
    public const float REQUIRES__BLOCKING = 2.5f;
    public const float REQUIRES__BEING_AT_FULL_ENERGY = 2.5f;
    public const float REQUIRES__BEING_BELOW_HALF_ENERGY = 1.75f;
    public const float REQUIRES__STACKING_UP_FLOW_FOR_MAXIMUM_VALUE = 3f;
    public const float REQUIRES__FLOW_RANK_S = 2.5f;
    public const float REQUIRES__SPENDING_ENERGY = 1.5f;
    public const float REQUIRES__NOT_ATTACKING_FOR_5_SECONDS_OR_ENTERING_STEALTH_ONCE_PER_15_SEC = 5.7f;
    public const float REQUIRES__NOT_TAKING_DAMAGE = 1.5f;

    //Multipliers for requiring certain condition
    public const float SPECIAL__APPLIES_5_SEC_STEALTH = 0.6666f;
    public const float SPECIAL__RESETS_ALL_OTHER_COOLDOWNS = 0.6666f;
    public const float SPECIAL__PERSISTS_FOR_10_SECONDS_AFTER_SWITCHING_OUT_OF_STANCE = 0.75f;
    public const float SPECIAL__SCALES_WITH_ACCUMULATED_PLUNDERING_FLAME = 0.2f;
    public const float SPECIAL__EXPECTED_RANK_OF_FLOW = 3f;
    public const float SPECIAL__EXPECTED_AMOUNT_OF_CONSECUTIVE_COUNTERS_WITHOUT_GETTING_HIT_BY_COUNTERABLE = 2f;
    public const float SPECIAL__STACKS_WHEN_NON_STOP_BASIC_ATTACKING = 0.35f;
    public const float SPECIAL__GIVE_2_EXTRA_HEALTH_POTION_CHARGES = 0.4f;
    public const float SPECIAL__GIVE_1_EXTRA_TOOL_CHARGES = 0.4f;
    public const float SPECIAL__MAKES_BASIC_ATTACKS_AND_TECHNIQUES_PERFORMED_IN_STEALTH_COUNT_AS_BACKSTABS = 0.75f;
    public const float SPECIAL__AFFECTS_EVERY_ENEMY_WITHIN_RANGE = 0.75f;
    public const float SPECIAL__AFFECTS_ALL_STACKING_EFFECTS = 0.45f;
    public const float SPECIAL__CONSUMES_LEFTOVER_ENERGY_AND_TRANSFORM_INTO_MULTIPLIER = 8f;
    public const float SPECIAL__REQUIRES_HITTING_2_SPLIT_ARROWS_TO_GET_FULL_VALUE = 2f;
    public const float SPECIAL__CONVERT_ALL_DAMAGE_DEPENDING_ON_WHICH_IS_LOWER = 0.4f;
    public const float SPECIAL__REMOVES_BURN_FREEZE_AND_BLEED_FROM_ENEMY = 2f;
    public const float SPECIAL__SCALES_WITH_ENEMY_DAMAGE_INSTEAD_OF_PLAYERS = 0.5f;
    public const float SPECIAL__SCALES_WITH_CURRENT_HEALTH_INSTEAD_OF_MAXIMUM = 1.6f;
    public const float SPECIAL__SCALES_WITH_MISSING_HEALTH_INSTEAD_OF_MAXIMUM = 1.8f;
    public const float SPECIAL__SCALES_WITH_MISSING_ENERGY = 1.5f;
    public const float SPECIAL__SCALES_WITH_ENERGY_SPENT = 1.5f;
    public const float SPECIAL__INCREASE_STAT_BASE_INSTEAD_OF_PERCENTAGE = 5f;
    public const float SPECIAL__TOTAL_HEALTH_AMOUNT_CONVERSION = 0.05714F;
    public const float SPECIAL__TOTAL_STAGGER_BAR_AMOUNT_CONVERSION = 0.05714F;
    public const float SPECIAL__STAT_BONUS_CONVERSION = 1.0f;
    public const float SPECIAL__BONUS_FOR_SCALING_WITH_BOTH_SELF_AND_ENEMY_DECAYING_EFFECT = 1.25f;
    public const float SPECIAL__BONUS_FOR_AFFECTING_2_DIFFERENT_STACKING_EFFECTS = 1.25f;
    public const float SPECIAL__BONUS_FOR_AFFECTING_3_DIFFERENT_STACKING_EFFECTS = 1.5f; //It is much harder to extract full value from all 3 stacking effects at the same time compared to just 1

    //Expected amount of certain stats or effects on average enemy
    public const float EXPECTED_AMOUNT_OF_REGULAR_ENEMY_HEALTH = 10; // 125 with Armor
    public const float EXPECTED_AMOUNT_OF_REGULAR_ENEMY_STAGGER_BAR = 5; // 62.5 with Armor
    public const float EXPECTED_AMOUNT_OF_BOSS_ENEMY_HEALTH = 100; // 1250 with Armor
    public const float EXPECTED_AMOUNT_OF_BOSS_ENEMY_STAGGER_BAR = 10; // 1250 with Armor
    public const float EXPECTED_AMOUNT_OF_ENEMY_ARMOR = 40;
    public const float EXPECTED_AMOUNT_OF_PLAYER_ARMOR = 80;
    public const float EXPECTED_AMOUNT_OF_DEBUFFS_ON_PLAYER = 3;
    public const float EXPECTED_AMOUNT_OF_DEBUFFS_ON_ENEMY = 3;
    public const float EXPECTED_AMOUNT_OF_SPECIFIC_ITEM_EQUIPPED = 3.0f;
    public const float EXPECTED_AMOUNT_OF_SCALING_STACKING_EFFECT_ON_PLAYER = 30;
    public const float EXPECTED_AMOUNT_OF_DAMAGING_STACKING_EFFECT_ON_PLAYER = 30;
    public const float EXPECTED_AMOUNT_OF_DAMAGING_STACKING_EFFECT_ON_ENEMY = 50;
    public const float EXPECTED_AMOUNT_OF_UNIQUE_STACKING_EFFECTS_ON_PLAYER_AND_ENEMY = EXPECTED_AMOUNT_OF_UNIQUE_STACKING_EFFECTS_ON_PLAYER + EXPECTED_AMOUNT_OF_UNIQUE_STACKING_EFFECTS_ON_ENEMY;
    public const float EXPECTED_AMOUNT_OF_UNIQUE_STACKING_EFFECTS_ON_PLAYER = 1.5f;
    public const float EXPECTED_AMOUNT_OF_UNIQUE_STACKING_EFFECTS_ON_ENEMY = 1.5f;


    //Stat Percentage Increase per 1 PB
    public const float DAMAGE_MULTIPLIER_PER_PB = 0.0025f;
    public const float DAMAGE_MULTIPLIER_PER_100_STACKING_EFFECT_PER_PB = 0.005f;
    public const float DAMAGE_MULTIPLIER_PER_1000_COMBINED_HEALTH_AND_STAGGER_BAR_PER_PB = 0.006f;
    public const float DAMAGE_INCREASE_PER_PB = 1f;
    public const float ANALYSIS_PERCENTAGE_EFFECTIVNESS_PER_PB = PRONE_PERCENTAGE_EFFECTIVNESS_PER_PB * ANALYSIS_PER_PB;
    public const float PRONE_PERCENTAGE_EFFECTIVNESS_PER_PB = 2f;
    public const float AMOUNT_OF_BARRIER_DECAY_MINIMUM_RAISED_BY_1000_HEALTH_OR_STAGGER_BAR_PER_PB = 0.2f;
    public const float DEAL_FLAT_DAMAGE_PER_PB = 10f;
    public const float DAMAGE_INCREASE_PER_1_ENEMY_ARMOR_PER_PB = 1 / PB.EXPECTED_AMOUNT_OF_ENEMY_ARMOR;
    public const float PERCENTAGE_ARMOR_PENETRATION_PER_PB = 1 / PB.EXPECTED_AMOUNT_OF_ENEMY_ARMOR;
    public const float MAXIMUM_STAGGER_BAR_INCREASE_PER_PB = 2f;
    public const float MAXIMUM_ENERGY_INCREASE_PER_PB = 0.5f;
    public const float MAXIMUM_HEALTH_INCREASE_PER_PB = 2f;
    public const float ATTACK_SPEED_INCREASE_PER_PB = 1.6f;
    public const float ENEMY_ATTACK_SPEED_DECREASE_PER_PB = 4f;
    public const float MOVEMENT_SPEED_INCREASE_PER_PB = 1.2f;
    public const float ENEMY_MOVEMENT_SPEED_DECREASE_PER_PB = 1.8f;
    public const float TOOL_POWER_INCREASE_PER_PB = 0.5f;
    public const float STANCE_POWER_INCREASE_PER_PB = 0.5f;
    public const float ITEM_POWER_INCREASE_PER_PB = 0.25f;
    public const float PASSIVE_POWER_UP_POWER_INCREASE_PER_PB = 0.25f;
    public const float HEALTH_POTION_POWER_INCREASE_PER_PB = 0.75f;
    public const float ARMOR_PER_PB = 1f;
    public const float PERCENTAGE_ARMOR_RETAINED_WHILE_STAGGERED_PER_PB = 0.5f;
    public const float STEAL_1P_OF_ENEMY_STAGGER_BAR_PER_PB = 0.1f;
    public const float REDUCE_1P_OF_ENEMY_STAGGER_BAR_PER_PB = 0.2f;
    public const float KNOCK_BACK_METERS_PER_PB = 0.2f;
    public const float TENACITY_INCREASE_PER_PB = 1.5f;
    public const float DODGE_INVINCIBILITY_DURATION_INCREASE_PER_PB = 0.4f;
    public const float STEALTH_DURATION_INCREASE_PER_PB = 2f;
    public const float FREEZE_DURATION_INCREASE_PER_PB = 1.25f;
    public const float FLAT_TENACITY_REDUCTION_PER_PB = 1.5f;
    public const float PERCENTAGE_TENACITY_REDUCTION_PER_PB = 0.5f;
    public const float CONTROL_INCREASE_PER_PB = 1.5f;
    public const float PERCENTAGE_REDUCED_ENERGY_COST_OF_GENERATING_1_AMMO_PER_PB = 1.25f;
    public const float ENERGY_GAIN_INCREASE_PER_PB = 1.25f;
    public const float FLAT_HEALTH_RESTORED_PER_PB = 0.2f;
    public const float PERCENTAGE_HEALTH_AND_STAGGER_BAR_CONSUMED_TO_EMPOWER_TECHNIQUE_DAMAGE_PER_PB = 0.5f;
    public const float MAXIMUM_HEALTH_AND_STAGGER_BAR_PERMANENTLY_STOLEN_PER_PB = 0.1f;
    public const float DURATION_OF_PROLONGING_ASSASSINATION_PER_PB = 0.096f;
    public const float MAXIMUM_HEALTH_AND_STAGGER_BAR_PERMANENTLY_REDUCED_PER_PB = 0.25f;
    public const float PERCENTAGE_OF_ENEMY_STAGGER_BAR_AS_FREEZE_REQUIRED_TO_INSTA_FROZEN_PER_PB = 0.0625f;
    public const float FLAT_HEALTH_RESTORED_PER_SECOND_PER_PB = 0.04f;
    public const float FLAT_STAGGER_BAR_RESTORED_PER_PB = 0.4f;
    public const float FLAT_STAGGER_BAR_RESTORED_PER_SECOND_PER_PB = 0.08f;
    public const float PERCENTAGE_HEALTH_RESTORED_PER_PB = 0.1f;
    public const float PERCENTAGE_HEALTH_RESTORED_PER_SECOND_PER_PB = 0.02f;
    public const float PERCENTAGE_STAGGER_BAR_RESTORED_PER_PB = 0.2f;
    public const float PERCENTAGE_STAGGER_BAR_RESTORED_PER_SECOND_PER_PB = 0.04f;
    public const float COOLDOWN_REDUCTION_INCREASE_PER_PB = 1.25f;
    public const float PERCENTAGE_OF_ORIGINAL_DAMAGE_DEALT_BY_TRIPLE_ARROWS_PER_PB = 0.8f;
    public const float EFFECT_AMOUNT_INCREASE_PER_PB = 2f;
    public const float BLOCK_DAMAGE_PER_PB = 10f;
    public const float REDUCE_DURATION_NEEDED_FOR_EFFECT_TO_ACTIVATE = 0.5f;
    public const float REDUCE_SPECIFIED_EFFECT_COOLDOWN_PER_PB = 0.5f;
    public const float EFFECT_DECAY_INCREASE_PER_PB = 3f;
    public const float PERCENTAGE_OF_HEAL_DAMAGE_DEALT_PER_PB = 0.1f;
    public const float PERCENTAGE_OF_HEALTH_RESTORED_PER_1_ENERGY_SPENT_PER_PB = 0.01f;
    public const float PERCENTAGE_OF_HEALTH_RESTORED_PER_1_M_TRAVELLED_PER_PB = 0.05f;
    public const float HEALTH_RESTORED_PER_INJURY_TAKEN_OVER_30_SECONDS_PER_PB = 0.004f;
    public const float PERCENTAGE_OF_DAMAGE_TAKEN_REFLECTED_PER_PB = 0.002f;
    public const float CONVERT_HALF_OF_DAMAGE_TYPE_DEALT_TO_PLAYER_INTO_THE_OTHER_AND_REDUCE_PER_PB = 0.3125f;
    public const float PERCENTAGE_OF_MAX_HEALTH_RESTORED_FOR_EACH_SECOND_OF_CC_APPLIED_PER_PB = 0.1f;
    public const float CONVERT_ONE_PERCENTAGE_OF_ONE_STAT_INTO_ANOTHER_PER_PB = 1;
    public const float PERCENTAGE_EFFECTIVNESS_OF_CONVERTING_ALL_INJURY_INTO_STACKING_EFFECT_PER_PB = 0.14285f;
    public const float CONVERT_1P_OF_DAMAGE_TAKEN_INTO_STACKING_EFFECT_PER_PB = 0.4f;
    public const float PERCENTAGE_CONVERSION_OF_USED_STACKING_EFFECT_INTO_HEALTH_AND_STAGGER_BAR_HEAL_PER_PB = 1.5f;
    public const float PERCENTAGE_CONVERSION_OF_DECAYED_STACKING_EFFECT_INTO_ANOTHER_PER_PB = 0.75f;
    public const float PERCENTAGE_CONVERSION_OF_ONE_STACKING_EFFECT_SPENT_INTO_ANOTHER_PER_PB = 0.5f;
    public const float PERCENTAGE_CONVERSION_OF_DAMAGING_EFFECT_INTO_EXTRA_DAMAGE_PER_PB = 20f;
    public const float REDUCE_ALL_REMAINING_COOLDOWNS_PERCENTAGE_PER_PB = 0.15f;
    public const float LEAVE_BEHIND_PERCENTAGE_OF_STACKS_ON_STAGGERING_PER_PB = 1f;
    public const float GAIN_FLAT_ENERGY_AFFECTED_BY_ENERGY_GAIN_PER_PB = 0.5f;
    public const float AMMO_PERCENTAGE_RESTORED_PER_PB = 1.8f;
    public const float APPLY_STACKING_EFFECT_PER_PB = 1f;
    public const float PERCENTAGE_EFFECTIVNESS_OF_CONVERSION_OF_STACKING_EFFECT_TO_STAT_PER_PB = 0.1f;
    public const float STACKING_EFFECT_GAINED_PER_1M_TRAVELLED_PER_PB = 0.1f;
    public const float BACKSTAB_REDUCED_COOLDOWN_PER_PB = 0.15f;
    public const float STACKING_EFFECT_GAINED_PER_10_HEALTH_LOST = 0.1f;
    public const float HEALTH_HEALED_PER_10_STACKING_EFFECT_LOST = 0.1f;
    public const float APPLY_PERCENTAGE_OF_DAMAGE_DEALT_AS_STACKING_EFFECT_PER_PB = 0.1f;
    public const float APPLY_PERCENTAGE_OF_DAMAGE_DEALT_OR_TAKEN_AS_STACKING_EFFECT_PER_PB = 0.05f;
    public const float DECREASE_STACKING_EFFECT_RECEIVED_PER_PB = 1.5f;
    public const float REMOVE_DAMAGING_STACKING_EFFECT_FROM_PLAYER_PER_PB = 0.5f;
    public const float PROJECTILE_MAX_DISTANCE_INCREASE_PERCENTAGE_PER_PB = 1.25f;
    public const float EXTRA_MAXIMUM_HEALTH_RESTORED_BY_HEALTH_POTION_PER_PB = PERCENTAGE_HEALTH_RESTORED_PER_SECOND_PER_PB * 10;
    public const float GLOBAL_STAGGER_BAR_REGENERATION_REDUCTION_PER_PB = PB.ENEMY_STAGGER_BAR_PER_PB / 160;
    public const float INCREASED_HEALTH_RESTORATION_POWER_PER_PB = 0.4f;
    public const float SECONDS_OF_STUN_PER_PB = 0.05f;
    public const float SECONDS_OF_STEALTH_PER_PB = 0.1f;
    public const float SECONDS_OF_INVINCIBILITY_PER_PB = 0.02f;
    public const float INCREASE_FLOW_STACKS_ACQUIRED_PERCENTAGE_PER_PB = 2f;


    //Flat Stats per 1 PB
    public const float PLAYER_HEALTH_PER_PB = 4f;
    public const float ENEMY_HEALTH_PER_PB = 8f;
    public const float PLAYER_STAGGER_BAR_PER_PB = 8f;
    public const float ENEMY_STAGGER_BAR_PER_PB = 8f;
    public const float DAMAGE_SCALING_PER_PB = 4f;
    public const float INJURY_SCALING_PER_PB = DAMAGE_SCALING_PER_PB * AFFECTS_ONLY__INJURY;
    public const float STAGGER_SCALING_PER_PB = DAMAGE_SCALING_PER_PB * AFFECTS_ONLY__STAGGER;
    private const float SCALING_STACKING_EFFECT_PER_PB = 1f;
    private const float DAMAGING_STACKING_EFFECT_PER_PB = 1f;


    //Effect amount per 1 PB
    public const float EMPOWERED_PER_PB = SCALING_STACKING_EFFECT_PER_PB;
    public const float ONSLAUGHT_PER_PB = SCALING_STACKING_EFFECT_PER_PB * AFFECTS_ONLY__BASIC_ATTACKS;
    public const float SHARP_PER_PB = SCALING_STACKING_EFFECT_PER_PB * AFFECTS_ONLY__RIPOSTES_AND_COUNTERS;
    public const float BURN_PER_PB = DAMAGING_STACKING_EFFECT_PER_PB * AFFECTS_ONLY__STAGGER * 0.6f;
    public const float FREEZE_PER_PB = DAMAGING_STACKING_EFFECT_PER_PB * AFFECTS_ONLY__STAGGER * 0.75f;
    public const float BARRIER_PER_PB = (PLAYER_HEALTH_PER_PB + ENEMY_HEALTH_PER_PB) / 2 * 1.5f;
    public const float BLEED_PER_PB = DAMAGING_STACKING_EFFECT_PER_PB * AFFECTS_ONLY__INJURY * 1.2f;
    public const float POISON_PER_PB = 0.5f;
    public const float SUPERCHARGE_PER_PB = DAMAGING_STACKING_EFFECT_PER_PB * 5f;
    public const float ACCELERATION_PER_PB = SCALING_STACKING_EFFECT_PER_PB * ATTACK_SPEED_INCREASE_PER_PB;
    public const float ANALYSIS_PER_PB = SCALING_STACKING_EFFECT_PER_PB * AFFECTS_ONLY__TECHNIQUES;
    public const float CHAINED_PER_PB = SCALING_STACKING_EFFECT_PER_PB * 1.2f;
    public const float SLEEP_PER_PB = SECONDS_OF_STUN_PER_PB * 4f;
    public const float LETHARGY_PER_PB = SCALING_STACKING_EFFECT_PER_PB * ENEMY_ATTACK_SPEED_DECREASE_PER_PB;
    public const float PRONE_PER_PB = SCALING_STACKING_EFFECT_PER_PB;
    public const float SLOW_PER_PB = ENEMY_MOVEMENT_SPEED_DECREASE_PER_PB * 3f;


    //Special effects per 1 PB
    public const float RESIST_FATAL_BLOW_AND_RESTORE_HEALTH_PER_PB = 0.05f;
    public const float PB_VALUE_OF_MAKING_PRONE_NOT_WORK_ON_NON_TOOL_DAMAGE = 30f;
}
